import { db } from './index.ts';
import { planOrders } from './schema.ts';
import { eq, and } from 'drizzle-orm';
import { assignPlan } from './vendorSubscriptions.ts';

/** `id` is generated by the caller (not left to defaultRandom()) — the
 * checkout route needs to know the order id before the row exists, to put
 * it in Paydunya's return_url. */
export async function createOrder(
  id: string,
  vendorId: string,
  planId: string,
  invoiceToken: string,
  amountFcfa: number
) {
  const result = await db.insert(planOrders).values({ id, vendorId, planId, invoiceToken, amountFcfa }).returning();
  return result[0];
}

export async function getOrder(id: string) {
  const rows = await db.select().from(planOrders).where(eq(planOrders.id, id)).limit(1);
  return rows[0] ?? null;
}

export async function getOrderByToken(invoiceToken: string) {
  const rows = await db.select().from(planOrders).where(eq(planOrders.invoiceToken, invoiceToken)).limit(1);
  return rows[0] ?? null;
}

export async function markOrderFailed(id: string) {
  await db
    .update(planOrders)
    .set({ status: 'FAILED' })
    .where(and(eq(planOrders.id, id), eq(planOrders.status, 'PENDING')));
}

/**
 * Called once Paydunya has confirmed the payment (see src/lib/paydunya.ts's
 * confirmInvoice — never on the strength of an IPN's own body, which this
 * function has no way to verify came from Paydunya at all).
 *
 * The status flip and the plan activation happen in one transaction, and
 * the flip itself is the atomic claim: two calls for the same order
 * (a duplicate IPN delivery racing the return-url sync check, which is
 * expected here — see the checkout route) resolve to exactly one of them
 * doing the UPDATE...WHERE status='PENDING' successfully. The other finds
 * 0 rows and returns null instead of creating a second subscription for
 * one payment.
 */
export async function completeOrderAndActivate(orderId: string) {
  return db.transaction(async (tx) => {
    const claimed = await tx
      .update(planOrders)
      .set({ status: 'COMPLETED', completedAt: new Date() })
      .where(and(eq(planOrders.id, orderId), eq(planOrders.status, 'PENDING')))
      .returning();
    if (claimed.length === 0) return null;

    const order = claimed[0];
    const subscription = await assignPlan(order.vendorId, order.planId, tx);
    return { order, subscription };
  });
}
