import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Hand-written from firebase-applet-config.json / src/lib/firebase.ts —
/// the same values the React web app already uses, not generated by the
/// FlutterFire CLI (no `flutterfire configure` here, no Firebase CLI
/// login available in this environment). These values are public client
/// config, not secrets, so copying them is safe.
///
/// Only `web` is filled in. Android/iOS need their own
/// google-services.json / GoogleService-Info.plist from the Firebase
/// console (Project settings > Add app), which nothing here can generate —
/// see MOBILE_README.md. Until those exist, Google sign-in is web-only
/// (see auth_service.dart); phone/PIN auth needs no Firebase config at all
/// and works on every platform already.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'No google-services.json configured for Android — see MOBILE_README.md.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'No GoogleService-Info.plist configured for iOS — see MOBILE_README.md.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions has not been configured for this platform.');
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyBhpo8sgf3mMr9dYC_oMGTL9vRjQmPl55A',
    appId: '1:929474690742:web:aa99529b6da7a80b30b017',
    messagingSenderId: '929474690742',
    projectId: 'ocass-8e158',
    authDomain: 'ocass-8e158.firebaseapp.com',
    storageBucket: 'ocass-8e158.firebasestorage.app',
  );
}
